## configuration to be excluded...
exclude_patterns:
- "tests/"
- "spec/"
- "**/vendor/"
- "swagger_ui/"
- "UI/"
- "config/"
- "db/"
- "dist/"
- "features/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
exclude_patterns:
  - "app/api/common/decorators.py"
  - "app/api/common/responses.py"
  - "app/database/database.py"