language: python

python:
  - "3.6.4"

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - source ./.travis.sh
  - psql -c "create role testuser with superuser login password 'testuser';" -U postgres
  - psql -c 'create database testdb;' -U postgres
  - psql -c 'alter database testdb owner to testuser' -U postgres

script:
  - nosetests --with-coverage --cover-package=app app/tests

after_success:
  - coveralls

notifications:
  email: false
